### ISSUE TITLE
Error with Webpack version 2.1.0-beta.26

### ISSUE THREAD

**Issue by blacksonic** [webpack/source-map-loader#20]
I get the following error after I ugraded my Webpack to 2.1.0-beta.26.

```
Error: Module '/home/blacksonic/workspace/angular2-config-generator/node_modules/source-map/source-map.js' is not a loader (must have normal or pitch function)
    at loadLoader (/home/blacksonic/workspace/angular2-config-generator/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/home/blacksonic/workspace/angular2-config-generator/node_modules/loader-runner/lib/LoaderRunner.js:164:2)
    at runLoaders (/home/blacksonic/workspace/angular2-config-generator/node_modules/loader-runner/lib/LoaderRunner.js:357:2)
    at NormalModule.doBuild (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModule.js:131:2)
    at NormalModule.build (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModule.js:179:15)
    at Compilation.buildModule (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/Compilation.js:127:9)
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/Compilation.js:306:10
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModuleFactory.js:74:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/blacksonic/workspace/angular2-config-generator/node_modules/tapable/lib/Tapable.js:123:70)
    at onDoneResolving (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModuleFactory.js:49:11)
    at onDoneResolving (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModuleFactory.js:165:6)
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/lib/NormalModuleFactory.js:161:6
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/node_modules/async/dist/async.js:3853:9
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/node_modules/async/dist/async.js:484:16
    at iteratorCallback (/home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/node_modules/async/dist/async.js:1084:13)
    at /home/blacksonic/workspace/angular2-config-generator/node_modules/webpack/node_modules/async/dist/async.js:988:16
```

**Comment by blacksonic** [comment]
The problem was with my rules configuration, the correct for mis ```source-map-loder```, missed the ```-loader``` suffix.
